### PR TITLE
Some generator fixes

### PR DESCRIPTION
**Pull request by Denny09310**
This PR addresses recent issues I encountered with the generator:

1. ~~It’s unclear if the problem stemmed from an update, but the latest nightly build wasn’t functioning properly. Specifically, it failed to initiate the process, returning no Visual Studio instances from `MSBuildLocator.QueryVisualStudioInstances()`~~.
  
2. ~~When using `GenerateComponentsFromAssemblyAttribute`, the generator consistently detected zero classes. After a step-by-step debug, I identified [this line](https://github.com/Dreamescaper/BlazorBindings.Maui/blob/5e75b42d5ed743035cf564a38fdd0d0ce76ab384/src/BlazorBindings.Maui.ComponentGenerator/Program.cs#L122) as the culprit, as it consistently evaluated to false~~.

3. Included the ability to create unique namespaces, this was because in my sample app I was having issues with the generator trying to generate two `using MC = ...` namespaces. One for the `Microsoft.Maui.Controls` and the other for a third party library called [`MauiIcons`](https://github.com/AathifMahir/MauiIcons)

4. Additionally, I included some code cleanup and updated the project to leverage new features in C# 13.

### CODE REVIEW

**Comment by Denny09310** [comment]
> How does it fix 1) ?

I'll remive 1 as it seems to be an update of some package and not really a fix. I don't know but packaging the branch 'generator_updates' make the tool work, while before was giving an error

**Comment by Dreamescaper** [comment]
Ah, ok. Pack is simply broken now, fixing it.

**Comment by Denny09310** [comment]
At this point I saw you fixed the 2nd problem as well. I'll take this open if you want to merge the cleanup and C# features changes 😄

**Comment by Dreamescaper** [comment]
I'm thinking simply to use full type name (e.g. `global::MauiIcons.MauiIcon`) for all non-MAUI types. Maybe a bit uglier generated file, but less possible problems.

**Comment by Denny09310** [comment]
Yes that could be a solution, if we suppose that after the generation the user should do minimal to no changes to the components it should not be bothered

**Comment by Dreamescaper** [comment]
Ha, I didn't know it automatically close the PR if I delete my branch :)

**Pull request closed without merging**
